on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: devcontainers/ci@v0.2
        with:
          imageName: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}
          imageTag: ${{ github.ref_name }}
          cacheFrom: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.ref_name }}
          push: always

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: devcontainers/ci@v0.2
        with:
          cacheFrom: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.ref_name }}
          push: never
          runCmd: echo "Hello from the devcontainer!"
